/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { HealthCheckGet$Params as HealthCheckGet$Params } from './fn/health/health-check-get';
export { healthCheckGet as healthCheckGet } from './fn/health/health-check-get';
export type { GetPainelAcessibilidadeAcessibilidadePainelGet$Params as GetPainelAcessibilidadeAcessibilidadePainelGet$Params } from './fn/acessibilidade/get-painel-acessibilidade-acessibilidade-painel-get';
export { getPainelAcessibilidadeAcessibilidadePainelGet as getPainelAcessibilidadeAcessibilidadePainelGet } from './fn/acessibilidade/get-painel-acessibilidade-acessibilidade-painel-get';
export type { GetPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet$Params as GetPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet$Params } from './fn/acessibilidade/get-painel-escolas-acessibilidade-acessibilidade-painel-escolas-get';
export { getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet as getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet } from './fn/acessibilidade/get-painel-escolas-acessibilidade-acessibilidade-painel-escolas-get';
export type { GetMapaAcessibilidadeAcessibilidadeMapaGet$Params as GetMapaAcessibilidadeAcessibilidadeMapaGet$Params } from './fn/acessibilidade/get-mapa-acessibilidade-acessibilidade-mapa-get';
export { getMapaAcessibilidadeAcessibilidadeMapaGet as getMapaAcessibilidadeAcessibilidadeMapaGet } from './fn/acessibilidade/get-mapa-acessibilidade-acessibilidade-mapa-get';
export type { GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params as GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params } from './fn/acessibilidade/get-analise-temporal-acessibilidade-acessibilidade-analise-temporal-get';
export { getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet as getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet } from './fn/acessibilidade/get-analise-temporal-acessibilidade-acessibilidade-analise-temporal-get';
export type { GetPainelConectividadeConectividadePainelGet$Params as GetPainelConectividadeConectividadePainelGet$Params } from './fn/conectividade/get-painel-conectividade-conectividade-painel-get';
export { getPainelConectividadeConectividadePainelGet as getPainelConectividadeConectividadePainelGet } from './fn/conectividade/get-painel-conectividade-conectividade-painel-get';
export type { GetPainelEscolasConectividadeConectividadePainelEscolasGet$Params as GetPainelEscolasConectividadeConectividadePainelEscolasGet$Params } from './fn/conectividade/get-painel-escolas-conectividade-conectividade-painel-escolas-get';
export { getPainelEscolasConectividadeConectividadePainelEscolasGet as getPainelEscolasConectividadeConectividadePainelEscolasGet } from './fn/conectividade/get-painel-escolas-conectividade-conectividade-painel-escolas-get';
export type { GetMapaConectividadeConectividadeMapaGet$Params as GetMapaConectividadeConectividadeMapaGet$Params } from './fn/conectividade/get-mapa-conectividade-conectividade-mapa-get';
export { getMapaConectividadeConectividadeMapaGet as getMapaConectividadeConectividadeMapaGet } from './fn/conectividade/get-mapa-conectividade-conectividade-mapa-get';
export type { GetAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet$Params as GetAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet$Params } from './fn/conectividade/get-analise-temporal-conectividade-conectividade-analise-temporal-get';
export { getAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet as getAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet } from './fn/conectividade/get-analise-temporal-conectividade-conectividade-analise-temporal-get';
export type { GetPainelInfraestruturaInfraestruturaPainelGet$Params as GetPainelInfraestruturaInfraestruturaPainelGet$Params } from './fn/infraestrutura/get-painel-infraestrutura-infraestrutura-painel-get';
export { getPainelInfraestruturaInfraestruturaPainelGet as getPainelInfraestruturaInfraestruturaPainelGet } from './fn/infraestrutura/get-painel-infraestrutura-infraestrutura-painel-get';
export type { GetPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet$Params as GetPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet$Params } from './fn/infraestrutura/get-painel-escolas-infraestrutura-infraestrutura-painel-escolas-get';
export { getPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet as getPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet } from './fn/infraestrutura/get-painel-escolas-infraestrutura-infraestrutura-painel-escolas-get';
export type { GetMapaInfraestruturaInfraestruturaMapaGet$Params as GetMapaInfraestruturaInfraestruturaMapaGet$Params } from './fn/infraestrutura/get-mapa-infraestrutura-infraestrutura-mapa-get';
export { getMapaInfraestruturaInfraestruturaMapaGet as getMapaInfraestruturaInfraestruturaMapaGet } from './fn/infraestrutura/get-mapa-infraestrutura-infraestrutura-mapa-get';
export type { GetAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet$Params as GetAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet$Params } from './fn/infraestrutura/get-analise-temporal-infraestrutura-infraestrutura-analise-temporal-get';
export { getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet as getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet } from './fn/infraestrutura/get-analise-temporal-infraestrutura-infraestrutura-analise-temporal-get';
export type { GetFiltrosFiltrosGet$Params as GetFiltrosFiltrosGet$Params } from './fn/filtros/get-filtros-filtros-get';
export { getFiltrosFiltrosGet as getFiltrosFiltrosGet } from './fn/filtros/get-filtros-filtros-get';
