/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiConfiguration } from './api-configuration';
export { RequestBuilder } from './request-builder';
export type { StrictHttpResponse } from './strict-http-response';


export type { AnaliseTemporalData } from './models/analise-temporal-data';
export type { AnaliseTemporalResponse } from './models/analise-temporal-response';
export type { FiltrosData } from './models/filtros-data';
export type { FiltrosResponse } from './models/filtros-response';
export type { Grafico } from './models/grafico';
export type { HttpValidationError } from './models/http-validation-error';
export type { MapaData } from './models/mapa-data';
export type { MapaPonto } from './models/mapa-ponto';
export type { MapaResponse } from './models/mapa-response';
export type { MetricaFiltro } from './models/metrica-filtro';
export type { MunicipioFiltro } from './models/municipio-filtro';
export type { Paginacao } from './models/paginacao';
export type { PainelData } from './models/painel-data';
export type { PainelDisponivel } from './models/painel-disponivel';
export type { PainelEscolasData } from './models/painel-escolas-data';
export type { PainelEscolasResponse } from './models/painel-escolas-response';
export type { PainelResponse } from './models/painel-response';
export type { PlotlyFigure } from './models/plotly-figure';
export type { ValidationError } from './models/validation-error';
export { BaseService } from './base-service';
export { HealthService } from './services/health.service';
export { AcessibilidadeService } from './services/acessibilidade.service';
export { FiltrosService } from './services/filtros.service';

export type { HealthCheckGet$Params as HealthCheckGet$Params } from './fn/health/health-check-get';
export { healthCheckGet as healthCheckGet } from './fn/health/health-check-get';
export type { GetPainelAcessibilidadeAcessibilidadePainelGet$Params as GetPainelAcessibilidadeAcessibilidadePainelGet$Params } from './fn/acessibilidade/get-painel-acessibilidade-acessibilidade-painel-get';
export { getPainelAcessibilidadeAcessibilidadePainelGet as getPainelAcessibilidadeAcessibilidadePainelGet } from './fn/acessibilidade/get-painel-acessibilidade-acessibilidade-painel-get';
export type { GetPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet$Params as GetPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet$Params } from './fn/acessibilidade/get-painel-escolas-acessibilidade-acessibilidade-painel-escolas-get';
export { getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet as getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet } from './fn/acessibilidade/get-painel-escolas-acessibilidade-acessibilidade-painel-escolas-get';
export type { GetMapaAcessibilidadeAcessibilidadeMapaGet$Params as GetMapaAcessibilidadeAcessibilidadeMapaGet$Params } from './fn/acessibilidade/get-mapa-acessibilidade-acessibilidade-mapa-get';
export { getMapaAcessibilidadeAcessibilidadeMapaGet as getMapaAcessibilidadeAcessibilidadeMapaGet } from './fn/acessibilidade/get-mapa-acessibilidade-acessibilidade-mapa-get';
export type { GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params as GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params } from './fn/acessibilidade/get-analise-temporal-acessibilidade-acessibilidade-analise-temporal-get';
export { getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet as getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet } from './fn/acessibilidade/get-analise-temporal-acessibilidade-acessibilidade-analise-temporal-get';
export type { GetFiltrosFiltrosGet$Params as GetFiltrosFiltrosGet$Params } from './fn/filtros/get-filtros-filtros-get';
export { getFiltrosFiltrosGet as getFiltrosFiltrosGet } from './fn/filtros/get-filtros-filtros-get';
