/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiConfiguration } from './api-configuration';
export { RequestBuilder } from './request-builder';
export type { StrictHttpResponse } from './strict-http-response';

export type { AnaliseTemporalData } from './models/analise-temporal-data';
export type { AnaliseTemporalFiltros } from './models/analise-temporal-filtros';
export type { AnaliseTemporalResponse } from './models/analise-temporal-response';
export type { DadosFiltros } from './models/dados-filtros';
export type { Grafico } from './models/grafico';
export type { HttpValidationError } from './models/http-validation-error';
export type { MapaData } from './models/mapa-data';
export type { MapaPonto } from './models/mapa-ponto';
export type { MapaResponse } from './models/mapa-response';
export type { MetricaFiltro } from './models/metrica-filtro';
export type { MunicipioFiltro } from './models/municipio-filtro';
export type { PainelData } from './models/painel-data';
export type { PainelResponse } from './models/painel-response';
export type { PlotlyFigure } from './models/plotly-figure';
export type { ValidationError } from './models/validation-error';
export { BaseService } from './base-service';
export { HealthService } from './services/health.service';
export { AcessibilidadeService } from './services/acessibilidade.service';

export type { HealthCheckGet$Params as HealthCheckGet$Params } from './fn/health/health-check-get';
export { healthCheckGet as healthCheckGet } from './fn/health/health-check-get';
export type { GetPainelAcessibilidadeAcessibilidadePainelGet$Params as GetPainelAcessibilidadeAcessibilidadePainelGet$Params } from './fn/acessibilidade/get-painel-acessibilidade-acessibilidade-painel-get';
export { getPainelAcessibilidadeAcessibilidadePainelGet as getPainelAcessibilidadeAcessibilidadePainelGet } from './fn/acessibilidade/get-painel-acessibilidade-acessibilidade-painel-get';
export type { GetMapaAcessibilidadeAcessibilidadeMapaGet$Params as GetMapaAcessibilidadeAcessibilidadeMapaGet$Params } from './fn/acessibilidade/get-mapa-acessibilidade-acessibilidade-mapa-get';
export { getMapaAcessibilidadeAcessibilidadeMapaGet as getMapaAcessibilidadeAcessibilidadeMapaGet } from './fn/acessibilidade/get-mapa-acessibilidade-acessibilidade-mapa-get';
export type { GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params as GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params } from './fn/acessibilidade/get-analise-temporal-acessibilidade-acessibilidade-analise-temporal-get';
export { getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet as getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet } from './fn/acessibilidade/get-analise-temporal-acessibilidade-acessibilidade-analise-temporal-get';
