/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AnaliseTemporalData } from './models/analise-temporal-data';
export type { AppSchemasAcessibilidadeAnaliseTemporalResponse } from './models/app-schemas-acessibilidade-analise-temporal-response';
export type { AppSchemasAcessibilidadeMapaData } from './models/app-schemas-acessibilidade-mapa-data';
export type { AppSchemasAcessibilidadeMapaPonto } from './models/app-schemas-acessibilidade-mapa-ponto';
export type { AppSchemasAcessibilidadeMapaResponse } from './models/app-schemas-acessibilidade-mapa-response';
export type { AppSchemasConectividadeAnaliseTemporalResponse } from './models/app-schemas-conectividade-analise-temporal-response';
export type { AppSchemasConectividadeMapaData } from './models/app-schemas-conectividade-mapa-data';
export type { AppSchemasConectividadeMapaPonto } from './models/app-schemas-conectividade-mapa-ponto';
export type { AppSchemasConectividadeMapaResponse } from './models/app-schemas-conectividade-mapa-response';
export type { AppSchemasInfraestruturaAnaliseTemporalResponse } from './models/app-schemas-infraestrutura-analise-temporal-response';
export type { AppSchemasInfraestruturaMapaData } from './models/app-schemas-infraestrutura-mapa-data';
export type { AppSchemasInfraestruturaMapaPonto } from './models/app-schemas-infraestrutura-mapa-ponto';
export type { AppSchemasInfraestruturaMapaResponse } from './models/app-schemas-infraestrutura-mapa-response';
export type { FiltrosData } from './models/filtros-data';
export type { FiltrosResponse } from './models/filtros-response';
export type { Grafico } from './models/grafico';
export type { HttpValidationError } from './models/http-validation-error';
export type { MetricaFiltro } from './models/metrica-filtro';
export type { MunicipioFiltro } from './models/municipio-filtro';
export type { Paginacao } from './models/paginacao';
export type { PainelData } from './models/painel-data';
export type { PainelDisponivel } from './models/painel-disponivel';
export type { PainelEscolasData } from './models/painel-escolas-data';
export type { PainelEscolasResponse } from './models/painel-escolas-response';
export type { PainelResponse } from './models/painel-response';
export type { PlotlyFigure } from './models/plotly-figure';
export type { ValidationError } from './models/validation-error';
