/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AnaliseTemporalData } from './models/analise-temporal-data';
export type { AnaliseTemporalResponse } from './models/analise-temporal-response';
export type { FiltrosData } from './models/filtros-data';
export type { FiltrosResponse } from './models/filtros-response';
export type { Grafico } from './models/grafico';
export type { HttpValidationError } from './models/http-validation-error';
export type { MapaData } from './models/mapa-data';
export type { MapaPonto } from './models/mapa-ponto';
export type { MapaResponse } from './models/mapa-response';
export type { MetricaFiltro } from './models/metrica-filtro';
export type { MunicipioFiltro } from './models/municipio-filtro';
export type { Paginacao } from './models/paginacao';
export type { PainelData } from './models/painel-data';
export type { PainelDisponivel } from './models/painel-disponivel';
export type { PainelEscolasData } from './models/painel-escolas-data';
export type { PainelEscolasResponse } from './models/painel-escolas-response';
export type { PainelResponse } from './models/painel-response';
export type { PlotlyFigure } from './models/plotly-figure';
export type { ValidationError } from './models/validation-error';
