/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AnaliseTemporalFiltros } from '../models/analise-temporal-filtros';
import { Grafico } from '../models/grafico';
export interface AnaliseTemporalData {
  /**
   * Opções disponíveis para popular dropdowns do frontend.
   */
  dados_filtros: AnaliseTemporalFiltros;

  /**
   * Mapa de gráficos da análise temporal, indexados por chave semântica.
   */
  graficos: {
    [key: string]: Grafico;
  };
}
