/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Grafico } from '../models/grafico';
export interface AnaliseTemporalData {

  /**
   * Mapa de gráficos da análise temporal, indexados por chave semântica.
   */
  graficos: {
[key: string]: Grafico;
};
}
