/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MetricaFiltro } from '../models/metrica-filtro';
export interface AnaliseTemporalFiltros {
  metricas: Array<MetricaFiltro>;
}
