/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Linha de gold.fato_score_acessibilidade: escola por ano censo com as 15
 * métricas e score/classificação de acessibilidade já pré-computados.
 */
export interface AppSchemasAcessibilidadeMapaPonto {
  classificacao_acessibilidade: 'Excelente' | 'Boa' | 'M\xE9dia' | 'Baixa' | 'Inexistente';
  co_entidade: number;
  dt_carga: (string | null);
  ideb_2023_anos_finais: (number | null);
  ideb_2023_anos_finais_mun: (number | null);
  ideb_2023_anos_iniciais: (number | null);
  ideb_2023_anos_iniciais_mun: (number | null);
  ideb_2023_ensino_medio: (number | null);
  ideb_2023_ensino_medio_mun: (number | null);
  in_acessibilidade_corrimao: number;
  in_acessibilidade_elevador: number;
  in_acessibilidade_inexistente: number;
  in_acessibilidade_pisos_tateis: number;
  in_acessibilidade_rampas: number;
  in_acessibilidade_sinal_sonoro: number;
  in_acessibilidade_sinal_tatil: number;
  in_acessibilidade_sinal_visual: number;
  in_acessibilidade_vao_livre: number;
  in_reserva_pcd: number;
  in_sala_atendimento_especial: number;
  nu_ano_censo: number;
  pibid: (number | null);
  qt_prof_assist_social: number;
  qt_prof_psicologo: number;
  qt_salas_utilizadas_acessiveis: number;
  score_acessibilidade: number;
  tp_aee: number;
}
