/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Escola por ano censo com as 17 métricas de infraestrutura e o score/
 * classificação calculados on-the-fly a partir de silver.infraestrutura_comum
 * (não há tabela pré-computada gold, notebook cell-9).
 *
 * O `score_infraestrutura` é a soma binária das 17 métricas (0–17). A
 * classificação segue as faixas do notebook (`classificar_infraestrutura`) e,
 * diferente dos outros painéis, NÃO tem faixa "Excelente".
 */
export interface AppSchemasInfraestruturaMapaPonto {
  classificacao_infraestrutura: 'Boa' | 'M\xE9dia' | 'Baixa' | 'Inexistente';
  co_entidade: number;
  in_agua_potavel: number;
  in_auditorio: number;
  in_banheiro: number;
  in_banheiro_pne: number;
  in_biblioteca: number;
  in_cozinha: number;
  in_energia_rede_publica: number;
  in_esgoto_rede_publica: number;
  in_laboratorio_ciencias: number;
  in_laboratorio_informatica: number;
  in_lixo_servico_coleta: number;
  in_patio_coberto: number;
  in_quadra_esportes: number;
  in_refeitorio: number;
  in_sala_atendimento_especial: number;
  in_sala_leitura: number;
  in_sala_multiuso: number;
  nu_ano_censo: number;
  pibid: (number | null);
  score_infraestrutura: number;
}
