/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppSchemasConectividadeMapaPonto } from '../models/app-schemas-conectividade-mapa-ponto';
export interface AppSchemasConectividadeMapaData {
  pontos: Array<AppSchemasConectividadeMapaPonto>;
}
