/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppSchemasAcessibilidadeMapaPonto } from '../models/app-schemas-acessibilidade-mapa-ponto';
export interface AppSchemasAcessibilidadeMapaData {
  pontos: Array<AppSchemasAcessibilidadeMapaPonto>;
}
