/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppSchemasInfraestruturaMapaPonto } from '../models/app-schemas-infraestrutura-mapa-ponto';
export interface AppSchemasInfraestruturaMapaData {
  pontos: Array<AppSchemasInfraestruturaMapaPonto>;
}
