/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Linha de gold.fato_score_conectividade: escola por ano censo com as 17
 * métricas e score/classificação de conectividade já pré-computados.
 *
 * O `score_conectividade` é o valor pré-computado pelo pipeline de dados — não
 * é a soma binária das 17 métricas (colunas qt_* somam a quantidade), então
 * excede 17 (observado até 26). Sem teto fixo no schema para não acoplar ao
 * intervalo do mart, cujo cálculo é de responsabilidade da squad de dados.
 */
export interface AppSchemasConectividadeMapaPonto {
  classificacao_conectividade: 'Boa' | 'M\xE9dia' | 'Baixa' | 'Inexistente';
  co_entidade: number;
  dt_carga: string | null;
  in_aces_internet_disp_pessoais: number;
  in_acesso_internet_computador: number;
  in_banda_larga: number;
  in_comp_portatil_aluno: number;
  in_computador: number;
  in_desktop_aluno: number;
  in_internet: number;
  in_internet_administrativo: number;
  in_internet_alunos: number;
  in_internet_aprendizagem: number;
  in_internet_comunidade: number;
  in_redes_sociais: number;
  in_tablet_aluno: number;
  nu_ano_censo: number;
  pibid: number | null;
  qt_comp_portatil_aluno: number;
  qt_desktop_aluno: number;
  qt_tablet_aluno: number;
  score_conectividade: number;
  tp_rede_local: number;
}
