/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MetricaFiltro } from '../models/metrica-filtro';
import { MunicipioFiltro } from '../models/municipio-filtro';
export interface DadosFiltros {
  anos: Array<number>;
  metricas: Array<MetricaFiltro>;
  municipios: Array<MunicipioFiltro>;
  rede_ensino: Array<'Federal' | 'Estadual' | 'Municipal' | 'Privada'>;
  tp_localizacao: Array<'Urbana' | 'Rural'>;
}
