/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MetricaFiltro } from '../models/metrica-filtro';
import { MunicipioFiltro } from '../models/municipio-filtro';

/**
 * Opções de filtro aplicáveis, compartilháveis entre painéis.
 */
export interface FiltrosData {
  /**
   * Anos de censo disponíveis.
   */
  anos: Array<number>;

  /**
   * Catálogo de métricas do painel informado em ?painel. Omitido quando nenhum painel é informado.
   */
  metricas?: Array<MetricaFiltro> | null;

  /**
   * Municípios disponíveis no recorte.
   */
  municipios: Array<MunicipioFiltro>;

  /**
   * Redes de ensino: Federal, Estadual, Municipal, Privada.
   */
  rede_ensino: Array<string>;

  /**
   * Tipos de localização: Urbana, Rural.
   */
  tp_localizacao: Array<string>;
}
