/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PlotlyFigure } from '../models/plotly-figure';

/**
 * Envelope de um gráfico do painel.
 */
export interface Grafico {

  /**
   * Figura Plotly (data + layout).
   */
  plotly: PlotlyFigure;

  /**
   * Tipo do gráfico (ex: 'radar', 'bar').
   */
  tipo: string;

  /**
   * Título legível para o frontend.
   */
  titulo: string;
}
