/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Escola georreferenciada com score e classificação de acessibilidade.
 */
export interface MapaPonto {
  classificacao_acessibilidade: 'Boa' | 'M\xE9dia' | 'Baixa' | 'Inexistente';
  co_entidade: number;
  latitude: number;
  longitude: number;
  no_bairro: (string | null);
  no_entidade: string;
  no_municipio: (string | null);
  no_tp_dependencia: (string | null);
  no_tp_localizacao: (string | null);
  score_acessibilidade: number;
}
