/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MetricaFiltro {

  /**
   * Identificador interno da métrica (ex: 'in_acessibilidade_rampas').
   */
  chave: string;

  /**
   * Label PT-BR para exibição (ex: 'Rampas').
   */
  label: string;
}
