/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Metadados de paginação do gráfico de métricas por escola.
 */
export interface Paginacao {

  /**
   * Página atual (base 0).
   */
  page: number;

  /**
   * Escolas por página.
   */
  page_size: number;

  /**
   * Total de escolas no recorte.
   */
  total_escolas: number;

  /**
   * Total de páginas disponíveis.
   */
  total_paginas: number;
}
