/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DadosFiltros } from '../models/dados-filtros';
import { Grafico } from '../models/grafico';
export interface PainelData {
  /**
   * Opções disponíveis para popular dropdowns do frontend.
   */
  dados_filtros: DadosFiltros;

  /**
   * Mapa de gráficos do painel, indexados por chave semântica.
   */
  graficos: {
    [key: string]: Grafico;
  };
}
