/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Grafico } from '../models/grafico';
import { Paginacao } from '../models/paginacao';
export interface PainelEscolasData {

  /**
   * Gráfico de métricas por escola (página atual).
   */
  grafico: Grafico;

  /**
   * Metadados de paginação.
   */
  paginacao: Paginacao;
}
