/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PainelDisponivel } from './painel-disponivel';

/**
 * Each possible value of `PainelDisponivel`
 */
export const PAINEL_DISPONIVEL: PainelDisponivel[] = [
  'acessibilidade'
];