/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Figura Plotly bruta: o que o frontend passa direto para o Plotly.react().
 */
export interface PlotlyFigure {
  /**
   * Traces do Plotly.
   */
  data: Array<{
    [key: string]: any;
  }>;

  /**
   * Layout do Plotly.
   */
  layout: {
    [key: string]: any;
  };

  [key: string]: any;
}
