/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FiltrosResponse } from '../../models/filtros-response';
import { PainelDisponivel } from '../../models/painel-disponivel';

export interface GetFiltrosFiltrosGet$Params {
  /**
   * Painel para incluir o catálogo de métricas (ex: acessibilidade). Se omitido, retorna apenas os filtros dimensionais.
   */
  painel?: PainelDisponivel | null;
}

export function getFiltrosFiltrosGet(
  http: HttpClient,
  rootUrl: string,
  params?: GetFiltrosFiltrosGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<FiltrosResponse>> {
  const rb = new RequestBuilder(rootUrl, getFiltrosFiltrosGet.PATH, 'get');
  if (params) {
    rb.query('painel', params.painel, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FiltrosResponse>;
    }),
  );
}

getFiltrosFiltrosGet.PATH = '/filtros';
