/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppSchemasConectividadeMapaResponse } from '../../models/app-schemas-conectividade-mapa-response';

export interface GetMapaConectividadeConectividadeMapaGet$Params {

/**
 * Ano do censo escolar (nu_ano_censo). Se omitido, retorna todos os anos.
 */
  ano?: (number | null);

/**
 * Filtro AND: a escola precisa ter TODAS as variáveis marcadas > 0. Conjunto das 17 métricas gold. Use o parâmetro repetido: ?variaveis=in_internet&variaveis=in_banda_larga.
 */
  variaveis?: (Array<'in_internet' | 'in_internet_alunos' | 'in_internet_administrativo' | 'in_internet_aprendizagem' | 'in_internet_comunidade' | 'in_banda_larga' | 'in_acesso_internet_computador' | 'in_aces_internet_disp_pessoais' | 'tp_rede_local' | 'in_computador' | 'in_desktop_aluno' | 'qt_desktop_aluno' | 'in_comp_portatil_aluno' | 'qt_comp_portatil_aluno' | 'in_tablet_aluno' | 'qt_tablet_aluno' | 'in_redes_sociais'> | null);

/**
 * Filtra escolas por participação no PIBID. true = só com PIBID; false = só sem PIBID; omitido = todas.
 */
  pibid?: (boolean | null);
}

export function getMapaConectividadeConectividadeMapaGet(http: HttpClient, rootUrl: string, params?: GetMapaConectividadeConectividadeMapaGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AppSchemasConectividadeMapaResponse>> {
  const rb = new RequestBuilder(rootUrl, getMapaConectividadeConectividadeMapaGet.PATH, 'get');
  if (params) {
    rb.query('ano', params.ano, {});
    rb.query('variaveis', params.variaveis, {});
    rb.query('pibid', params.pibid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppSchemasConectividadeMapaResponse>;
    })
  );
}

getMapaConectividadeConectividadeMapaGet.PATH = '/conectividade/mapa';
