/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AnaliseTemporalResponse } from '../../models/analise-temporal-response';

export interface GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params {
  /**
   * Métrica de acessibilidade a plotar. Valores aceitos: in_acessibilidade_rampas, in_acessibilidade_corrimao, in_acessibilidade_elevador, in_acessibilidade_pisos_tateis, in_acessibilidade_vao_livre, in_banheiro_pne.
   */
  metrica?: string;
}

export function getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet(
  http: HttpClient,
  rootUrl: string,
  params?: GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<AnaliseTemporalResponse>> {
  const rb = new RequestBuilder(
    rootUrl,
    getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet.PATH,
    'get',
  );
  if (params) {
    rb.query('metrica', params.metrica, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AnaliseTemporalResponse>;
    }),
  );
}

getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet.PATH =
  '/acessibilidade/analise-temporal';
