/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PainelResponse } from '../../models/painel-response';

export interface GetPainelAcessibilidadeAcessibilidadePainelGet$Params {
  /**
   * Ano do censo escolar (ex: 2023). Se omitido, agrega todos os censos.
   */
  ano?: number | null;

  /**
   * Lista de municípios (até 4). Use o parâmetro repetido: ?municipios=Belém&municipios=Ananindeua. Se omitido, o tab_percent cobre todos os municípios do recorte.
   */
  municipios?: Array<string> | null;

  /**
   * Filtro AND: escolas precisam ter TODAS as variáveis marcadas = 1.
   */
  variaveis?: Array<
    | 'in_banheiro_pne'
    | 'in_sala_atendimento_especial'
    | 'in_acessibilidade_rampas'
    | 'in_acessibilidade_corrimao'
    | 'in_acessibilidade_elevador'
    | 'in_acessibilidade_pisos_tateis'
    | 'in_acessibilidade_vao_livre'
    | 'in_acessibilidade_inexistente'
    | 'in_acessibilidade_sinal_tatil'
    | 'in_acessibilidade_sinal_sonoro'
    | 'in_acessibilidade_sinal_visual'
    | 'in_acessibilidade_sinalizacao'
    | 'in_prof_psicologo'
    | 'in_prof_trad_libras'
    | 'in_prof_revisor_braille'
    | 'in_prof_assist_social'
    | 'in_prof_fonaudiologo'
  > | null;

  /**
   * Rede(s) de ensino: Federal, Estadual, Municipal, Privada.
   */
  rede_ensino?: Array<'Federal' | 'Estadual' | 'Municipal' | 'Privada'> | null;

  /**
   * Localização da escola: Urbana ou Rural.
   */
  tp_localizacao?: Array<'Urbana' | 'Rural'> | null;
}

export function getPainelAcessibilidadeAcessibilidadePainelGet(
  http: HttpClient,
  rootUrl: string,
  params?: GetPainelAcessibilidadeAcessibilidadePainelGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PainelResponse>> {
  const rb = new RequestBuilder(
    rootUrl,
    getPainelAcessibilidadeAcessibilidadePainelGet.PATH,
    'get',
  );
  if (params) {
    rb.query('ano', params.ano, {});
    rb.query('municipios', params.municipios, {});
    rb.query('variaveis', params.variaveis, {});
    rb.query('rede_ensino', params.rede_ensino, {});
    rb.query('tp_localizacao', params.tp_localizacao, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PainelResponse>;
    }),
  );
}

getPainelAcessibilidadeAcessibilidadePainelGet.PATH = '/acessibilidade/painel';
