/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppSchemasAcessibilidadeAnaliseTemporalResponse } from '../../models/app-schemas-acessibilidade-analise-temporal-response';

export interface GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params {

/**
 * Métrica de acessibilidade a plotar nos dois gráficos.
 */
  metrica?: 'in_acessibilidade_rampas' | 'in_acessibilidade_corrimao' | 'in_acessibilidade_elevador' | 'in_acessibilidade_pisos_tateis' | 'in_acessibilidade_vao_livre' | 'qt_salas_utilizadas_acessiveis' | 'in_acessibilidade_inexistente' | 'in_acessibilidade_sinal_tatil' | 'in_acessibilidade_sinal_sonoro' | 'in_acessibilidade_sinal_visual' | 'tp_aee' | 'in_sala_atendimento_especial' | 'in_reserva_pcd' | 'qt_prof_psicologo' | 'qt_prof_assist_social';

/**
 * Filtra escolas por participação no PIBID. true = só com PIBID; false = só sem PIBID; omitido = todas.
 */
  pibid?: (boolean | null);
}

export function getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet(http: HttpClient, rootUrl: string, params?: GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AppSchemasAcessibilidadeAnaliseTemporalResponse>> {
  const rb = new RequestBuilder(rootUrl, getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet.PATH, 'get');
  if (params) {
    rb.query('metrica', params.metrica, {});
    rb.query('pibid', params.pibid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppSchemasAcessibilidadeAnaliseTemporalResponse>;
    })
  );
}

getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet.PATH = '/acessibilidade/analise-temporal';
