/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AppSchemasAcessibilidadeAnaliseTemporalResponse } from '../models/app-schemas-acessibilidade-analise-temporal-response';
import { AppSchemasAcessibilidadeMapaResponse } from '../models/app-schemas-acessibilidade-mapa-response';
import { getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet } from '../fn/acessibilidade/get-analise-temporal-acessibilidade-acessibilidade-analise-temporal-get';
import { GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params } from '../fn/acessibilidade/get-analise-temporal-acessibilidade-acessibilidade-analise-temporal-get';
import { getMapaAcessibilidadeAcessibilidadeMapaGet } from '../fn/acessibilidade/get-mapa-acessibilidade-acessibilidade-mapa-get';
import { GetMapaAcessibilidadeAcessibilidadeMapaGet$Params } from '../fn/acessibilidade/get-mapa-acessibilidade-acessibilidade-mapa-get';
import { getPainelAcessibilidadeAcessibilidadePainelGet } from '../fn/acessibilidade/get-painel-acessibilidade-acessibilidade-painel-get';
import { GetPainelAcessibilidadeAcessibilidadePainelGet$Params } from '../fn/acessibilidade/get-painel-acessibilidade-acessibilidade-painel-get';
import { getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet } from '../fn/acessibilidade/get-painel-escolas-acessibilidade-acessibilidade-painel-escolas-get';
import { GetPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet$Params } from '../fn/acessibilidade/get-painel-escolas-acessibilidade-acessibilidade-painel-escolas-get';
import { PainelEscolasResponse } from '../models/painel-escolas-response';
import { PainelResponse } from '../models/painel-response';

@Injectable({ providedIn: 'root' })
export class AcessibilidadeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPainelAcessibilidadeAcessibilidadePainelGet()` */
  static readonly GetPainelAcessibilidadeAcessibilidadePainelGetPath = '/acessibilidade/painel';

  /**
   * Painel de acessibilidade (gráfico + filtros disponíveis).
   *
   * Retorna o painel completo: gráfico tab_percent (barras horizontais por
   * município para a métrica escolhida) + opções de filtro (municípios, anos
   * e métricas) para popular dropdowns do frontend.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPainelAcessibilidadeAcessibilidadePainelGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelAcessibilidadeAcessibilidadePainelGet$Response(
    params?: GetPainelAcessibilidadeAcessibilidadePainelGet$Params,
    context?: HttpContext,
  ): Promise<StrictHttpResponse<PainelResponse>> {
    const obs = getPainelAcessibilidadeAcessibilidadePainelGet(
      this.http,
      this.rootUrl,
      params,
      context,
    );
    return firstValueFrom(obs);
  }

  /**
   * Painel de acessibilidade (gráfico + filtros disponíveis).
   *
   * Retorna o painel completo: gráfico tab_percent (barras horizontais por
   * município para a métrica escolhida) + opções de filtro (municípios, anos
   * e métricas) para popular dropdowns do frontend.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPainelAcessibilidadeAcessibilidadePainelGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelAcessibilidadeAcessibilidadePainelGet(
    params?: GetPainelAcessibilidadeAcessibilidadePainelGet$Params,
    context?: HttpContext,
  ): Promise<PainelResponse> {
    const resp = this.getPainelAcessibilidadeAcessibilidadePainelGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<PainelResponse>): PainelResponse => r.body);
  }

  /** Path part for operation `getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet()` */
  static readonly GetPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGetPath =
    '/acessibilidade/painel/escolas';

  /**
   * Gráfico paginado de métricas de acessibilidade por escola.
   *
   * Retorna uma página do gráfico de métricas por escola (barras empilhadas,
   * ordenado por score DESC) + metadados de paginação. Pensado para o frontend
   * navegar as demais escolas sem reprocessar o painel inteiro.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet$Response(
    params?: GetPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet$Params,
    context?: HttpContext,
  ): Promise<StrictHttpResponse<PainelEscolasResponse>> {
    const obs = getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet(
      this.http,
      this.rootUrl,
      params,
      context,
    );
    return firstValueFrom(obs);
  }

  /**
   * Gráfico paginado de métricas de acessibilidade por escola.
   *
   * Retorna uma página do gráfico de métricas por escola (barras empilhadas,
   * ordenado por score DESC) + metadados de paginação. Pensado para o frontend
   * navegar as demais escolas sem reprocessar o painel inteiro.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet(
    params?: GetPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet$Params,
    context?: HttpContext,
  ): Promise<PainelEscolasResponse> {
    const resp = this.getPainelEscolasAcessibilidadeAcessibilidadePainelEscolasGet$Response(
      params,
      context,
    );
    return resp.then(
      (r: StrictHttpResponse<PainelEscolasResponse>): PainelEscolasResponse => r.body,
    );
  }

  /** Path part for operation `getMapaAcessibilidadeAcessibilidadeMapaGet()` */
  static readonly GetMapaAcessibilidadeAcessibilidadeMapaGetPath = '/acessibilidade/mapa';

  /**
   * Escolas com score e classificação de acessibilidade pré-computados.
   *
   * Retorna as linhas de gold.fato_score_acessibilidade (uma por escola por
   * ano censo) com as 15 métricas e o score (0-15) e classificação
   * (Boa/Média/Baixa/Inexistente) já pré-computados pelo pipeline de dados.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMapaAcessibilidadeAcessibilidadeMapaGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMapaAcessibilidadeAcessibilidadeMapaGet$Response(
    params?: GetMapaAcessibilidadeAcessibilidadeMapaGet$Params,
    context?: HttpContext,
  ): Promise<StrictHttpResponse<AppSchemasAcessibilidadeMapaResponse>> {
    const obs = getMapaAcessibilidadeAcessibilidadeMapaGet(
      this.http,
      this.rootUrl,
      params,
      context,
    );
    return firstValueFrom(obs);
  }

  /**
   * Escolas com score e classificação de acessibilidade pré-computados.
   *
   * Retorna as linhas de gold.fato_score_acessibilidade (uma por escola por
   * ano censo) com as 15 métricas e o score (0-15) e classificação
   * (Boa/Média/Baixa/Inexistente) já pré-computados pelo pipeline de dados.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMapaAcessibilidadeAcessibilidadeMapaGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMapaAcessibilidadeAcessibilidadeMapaGet(
    params?: GetMapaAcessibilidadeAcessibilidadeMapaGet$Params,
    context?: HttpContext,
  ): Promise<AppSchemasAcessibilidadeMapaResponse> {
    const resp = this.getMapaAcessibilidadeAcessibilidadeMapaGet$Response(params, context);
    return resp.then(
      (
        r: StrictHttpResponse<AppSchemasAcessibilidadeMapaResponse>,
      ): AppSchemasAcessibilidadeMapaResponse => r.body,
    );
  }

  /** Path part for operation `getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet()` */
  static readonly GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGetPath =
    '/acessibilidade/analise-temporal';

  /**
   * Evolução temporal da acessibilidade (por localização e por dependência).
   *
   * Retorna os gráficos de evolução temporal: por tipo de localização
   * (uma linha por urbana/rural) e por tipo de dependência administrativa
   * (uma linha por Federal/Estadual/Municipal/Privada), ambos ao longo
   * dos anos censo + opções de filtro de métrica para popular dropdowns
   * do frontend.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Response(
    params?: GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params,
    context?: HttpContext,
  ): Promise<StrictHttpResponse<AppSchemasAcessibilidadeAnaliseTemporalResponse>> {
    const obs = getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet(
      this.http,
      this.rootUrl,
      params,
      context,
    );
    return firstValueFrom(obs);
  }

  /**
   * Evolução temporal da acessibilidade (por localização e por dependência).
   *
   * Retorna os gráficos de evolução temporal: por tipo de localização
   * (uma linha por urbana/rural) e por tipo de dependência administrativa
   * (uma linha por Federal/Estadual/Municipal/Privada), ambos ao longo
   * dos anos censo + opções de filtro de métrica para popular dropdowns
   * do frontend.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet(
    params?: GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params,
    context?: HttpContext,
  ): Promise<AppSchemasAcessibilidadeAnaliseTemporalResponse> {
    const resp = this.getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Response(
      params,
      context,
    );
    return resp.then(
      (
        r: StrictHttpResponse<AppSchemasAcessibilidadeAnaliseTemporalResponse>,
      ): AppSchemasAcessibilidadeAnaliseTemporalResponse => r.body,
    );
  }
}
