/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AnaliseTemporalResponse } from '../models/analise-temporal-response';
import { getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet } from '../fn/acessibilidade/get-analise-temporal-acessibilidade-acessibilidade-analise-temporal-get';
import { GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params } from '../fn/acessibilidade/get-analise-temporal-acessibilidade-acessibilidade-analise-temporal-get';
import { getMapaAcessibilidadeAcessibilidadeMapaGet } from '../fn/acessibilidade/get-mapa-acessibilidade-acessibilidade-mapa-get';
import { GetMapaAcessibilidadeAcessibilidadeMapaGet$Params } from '../fn/acessibilidade/get-mapa-acessibilidade-acessibilidade-mapa-get';
import { getPainelAcessibilidadeAcessibilidadePainelGet } from '../fn/acessibilidade/get-painel-acessibilidade-acessibilidade-painel-get';
import { GetPainelAcessibilidadeAcessibilidadePainelGet$Params } from '../fn/acessibilidade/get-painel-acessibilidade-acessibilidade-painel-get';
import { MapaResponse } from '../models/mapa-response';
import { PainelResponse } from '../models/painel-response';

@Injectable({ providedIn: 'root' })
export class AcessibilidadeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPainelAcessibilidadeAcessibilidadePainelGet()` */
  static readonly GetPainelAcessibilidadeAcessibilidadePainelGetPath = '/acessibilidade/painel';

  /**
   * Painel de acessibilidade (gráfico + filtros disponíveis).
   *
   * Retorna o painel completo: gráfico tab_percent (barras horizontais por
   * município para a métrica escolhida) + opções de filtro (municípios, anos
   * e métricas) para popular dropdowns do frontend.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPainelAcessibilidadeAcessibilidadePainelGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelAcessibilidadeAcessibilidadePainelGet$Response(
    params?: GetPainelAcessibilidadeAcessibilidadePainelGet$Params,
    context?: HttpContext,
  ): Promise<StrictHttpResponse<PainelResponse>> {
    const obs = getPainelAcessibilidadeAcessibilidadePainelGet(
      this.http,
      this.rootUrl,
      params,
      context,
    );
    return firstValueFrom(obs);
  }

  /**
   * Painel de acessibilidade (gráfico + filtros disponíveis).
   *
   * Retorna o painel completo: gráfico tab_percent (barras horizontais por
   * município para a métrica escolhida) + opções de filtro (municípios, anos
   * e métricas) para popular dropdowns do frontend.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPainelAcessibilidadeAcessibilidadePainelGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelAcessibilidadeAcessibilidadePainelGet(
    params?: GetPainelAcessibilidadeAcessibilidadePainelGet$Params,
    context?: HttpContext,
  ): Promise<PainelResponse> {
    const resp = this.getPainelAcessibilidadeAcessibilidadePainelGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<PainelResponse>): PainelResponse => r.body);
  }

  /** Path part for operation `getMapaAcessibilidadeAcessibilidadeMapaGet()` */
  static readonly GetMapaAcessibilidadeAcessibilidadeMapaGetPath = '/acessibilidade/mapa';

  /**
   * Pontos georreferenciados de escolas com score de acessibilidade.
   *
   * Retorna lista de escolas georreferenciadas (latitude/longitude) com
   * score (0-11) e classificação (Boa/Média/Baixa/Inexistente) de
   * acessibilidade calculados em SQL a partir de silver.fato_acessibilidade
   * e dimensões associadas.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMapaAcessibilidadeAcessibilidadeMapaGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMapaAcessibilidadeAcessibilidadeMapaGet$Response(
    params?: GetMapaAcessibilidadeAcessibilidadeMapaGet$Params,
    context?: HttpContext,
  ): Promise<StrictHttpResponse<MapaResponse>> {
    const obs = getMapaAcessibilidadeAcessibilidadeMapaGet(
      this.http,
      this.rootUrl,
      params,
      context,
    );
    return firstValueFrom(obs);
  }

  /**
   * Pontos georreferenciados de escolas com score de acessibilidade.
   *
   * Retorna lista de escolas georreferenciadas (latitude/longitude) com
   * score (0-11) e classificação (Boa/Média/Baixa/Inexistente) de
   * acessibilidade calculados em SQL a partir de silver.fato_acessibilidade
   * e dimensões associadas.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMapaAcessibilidadeAcessibilidadeMapaGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMapaAcessibilidadeAcessibilidadeMapaGet(
    params?: GetMapaAcessibilidadeAcessibilidadeMapaGet$Params,
    context?: HttpContext,
  ): Promise<MapaResponse> {
    const resp = this.getMapaAcessibilidadeAcessibilidadeMapaGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<MapaResponse>): MapaResponse => r.body);
  }

  /** Path part for operation `getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet()` */
  static readonly GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGetPath =
    '/acessibilidade/analise-temporal';

  /**
   * Evolução temporal da acessibilidade por tipo de localização.
   *
   * Retorna o gráfico de evolução temporal por tipo de localização
   * (uma linha por urbana/rural ao longo dos anos censo) + opções de
   * filtro de métrica para popular dropdowns do frontend.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Response(
    params?: GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params,
    context?: HttpContext,
  ): Promise<StrictHttpResponse<AnaliseTemporalResponse>> {
    const obs = getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet(
      this.http,
      this.rootUrl,
      params,
      context,
    );
    return firstValueFrom(obs);
  }

  /**
   * Evolução temporal da acessibilidade por tipo de localização.
   *
   * Retorna o gráfico de evolução temporal por tipo de localização
   * (uma linha por urbana/rural ao longo dos anos censo) + opções de
   * filtro de métrica para popular dropdowns do frontend.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet(
    params?: GetAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Params,
    context?: HttpContext,
  ): Promise<AnaliseTemporalResponse> {
    const resp = this.getAnaliseTemporalAcessibilidadeAcessibilidadeAnaliseTemporalGet$Response(
      params,
      context,
    );
    return resp.then(
      (r: StrictHttpResponse<AnaliseTemporalResponse>): AnaliseTemporalResponse => r.body,
    );
  }
}
