/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AppSchemasConectividadeAnaliseTemporalResponse } from '../models/app-schemas-conectividade-analise-temporal-response';
import { AppSchemasConectividadeMapaResponse } from '../models/app-schemas-conectividade-mapa-response';
import { getAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet } from '../fn/conectividade/get-analise-temporal-conectividade-conectividade-analise-temporal-get';
import { GetAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet$Params } from '../fn/conectividade/get-analise-temporal-conectividade-conectividade-analise-temporal-get';
import { getMapaConectividadeConectividadeMapaGet } from '../fn/conectividade/get-mapa-conectividade-conectividade-mapa-get';
import { GetMapaConectividadeConectividadeMapaGet$Params } from '../fn/conectividade/get-mapa-conectividade-conectividade-mapa-get';
import { getPainelConectividadeConectividadePainelGet } from '../fn/conectividade/get-painel-conectividade-conectividade-painel-get';
import { GetPainelConectividadeConectividadePainelGet$Params } from '../fn/conectividade/get-painel-conectividade-conectividade-painel-get';
import { getPainelEscolasConectividadeConectividadePainelEscolasGet } from '../fn/conectividade/get-painel-escolas-conectividade-conectividade-painel-escolas-get';
import { GetPainelEscolasConectividadeConectividadePainelEscolasGet$Params } from '../fn/conectividade/get-painel-escolas-conectividade-conectividade-painel-escolas-get';
import { PainelEscolasResponse } from '../models/painel-escolas-response';
import { PainelResponse } from '../models/painel-response';

@Injectable({ providedIn: 'root' })
export class ConectividadeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPainelConectividadeConectividadePainelGet()` */
  static readonly GetPainelConectividadeConectividadePainelGetPath = '/conectividade/painel';

  /**
   * Painel de conectividade (gráficos + cards).
   *
   * Retorna o painel completo de conectividade: cards de total de escolas,
   * tab_percent (barras horizontais por município), barras por dependência e
   * por tipo de localização para a(s) métrica(s) escolhida(s).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPainelConectividadeConectividadePainelGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelConectividadeConectividadePainelGet$Response(params?: GetPainelConectividadeConectividadePainelGet$Params, context?: HttpContext): Promise<StrictHttpResponse<PainelResponse>> {
    const obs = getPainelConectividadeConectividadePainelGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Painel de conectividade (gráficos + cards).
   *
   * Retorna o painel completo de conectividade: cards de total de escolas,
   * tab_percent (barras horizontais por município), barras por dependência e
   * por tipo de localização para a(s) métrica(s) escolhida(s).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPainelConectividadeConectividadePainelGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelConectividadeConectividadePainelGet(params?: GetPainelConectividadeConectividadePainelGet$Params, context?: HttpContext): Promise<PainelResponse> {
    const resp = this.getPainelConectividadeConectividadePainelGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<PainelResponse>): PainelResponse => r.body);
  }

  /** Path part for operation `getPainelEscolasConectividadeConectividadePainelEscolasGet()` */
  static readonly GetPainelEscolasConectividadeConectividadePainelEscolasGetPath = '/conectividade/painel/escolas';

  /**
   * Gráfico paginado de métricas de conectividade por escola.
   *
   * Retorna uma página do gráfico de métricas por escola (barras empilhadas,
   * ordenado por score DESC) + metadados de paginação.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPainelEscolasConectividadeConectividadePainelEscolasGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelEscolasConectividadeConectividadePainelEscolasGet$Response(params?: GetPainelEscolasConectividadeConectividadePainelEscolasGet$Params, context?: HttpContext): Promise<StrictHttpResponse<PainelEscolasResponse>> {
    const obs = getPainelEscolasConectividadeConectividadePainelEscolasGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Gráfico paginado de métricas de conectividade por escola.
   *
   * Retorna uma página do gráfico de métricas por escola (barras empilhadas,
   * ordenado por score DESC) + metadados de paginação.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPainelEscolasConectividadeConectividadePainelEscolasGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelEscolasConectividadeConectividadePainelEscolasGet(params?: GetPainelEscolasConectividadeConectividadePainelEscolasGet$Params, context?: HttpContext): Promise<PainelEscolasResponse> {
    const resp = this.getPainelEscolasConectividadeConectividadePainelEscolasGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<PainelEscolasResponse>): PainelEscolasResponse => r.body);
  }

  /** Path part for operation `getMapaConectividadeConectividadeMapaGet()` */
  static readonly GetMapaConectividadeConectividadeMapaGetPath = '/conectividade/mapa';

  /**
   * Escolas com score e classificação de conectividade pré-computados.
   *
   * Retorna as linhas de gold.fato_score_conectividade (uma por escola por
   * ano censo) com as 17 métricas e o score e classificação
   * (Excelente/Boa/Média/Baixa/Inexistente) já pré-computados pelo pipeline de dados. O
   * score pré-computado não é binário (colunas qt_* somam quantidade), então
   * excede 17.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMapaConectividadeConectividadeMapaGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMapaConectividadeConectividadeMapaGet$Response(params?: GetMapaConectividadeConectividadeMapaGet$Params, context?: HttpContext): Promise<StrictHttpResponse<AppSchemasConectividadeMapaResponse>> {
    const obs = getMapaConectividadeConectividadeMapaGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Escolas com score e classificação de conectividade pré-computados.
   *
   * Retorna as linhas de gold.fato_score_conectividade (uma por escola por
   * ano censo) com as 17 métricas e o score e classificação
   * (Excelente/Boa/Média/Baixa/Inexistente) já pré-computados pelo pipeline de dados. O
   * score pré-computado não é binário (colunas qt_* somam quantidade), então
   * excede 17.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMapaConectividadeConectividadeMapaGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMapaConectividadeConectividadeMapaGet(params?: GetMapaConectividadeConectividadeMapaGet$Params, context?: HttpContext): Promise<AppSchemasConectividadeMapaResponse> {
    const resp = this.getMapaConectividadeConectividadeMapaGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<AppSchemasConectividadeMapaResponse>): AppSchemasConectividadeMapaResponse => r.body);
  }

  /** Path part for operation `getAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet()` */
  static readonly GetAnaliseTemporalConectividadeConectividadeAnaliseTemporalGetPath = '/conectividade/analise-temporal';

  /**
   * Evolução temporal da conectividade (por localização e por dependência).
   *
   * Retorna os gráficos de evolução temporal: por tipo de localização
   * (uma linha por urbana/rural) e por tipo de dependência administrativa
   * (uma linha por Federal/Estadual/Municipal/Privada), ambos ao longo
   * dos anos censo.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet$Response(params?: GetAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet$Params, context?: HttpContext): Promise<StrictHttpResponse<AppSchemasConectividadeAnaliseTemporalResponse>> {
    const obs = getAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Evolução temporal da conectividade (por localização e por dependência).
   *
   * Retorna os gráficos de evolução temporal: por tipo de localização
   * (uma linha por urbana/rural) e por tipo de dependência administrativa
   * (uma linha por Federal/Estadual/Municipal/Privada), ambos ao longo
   * dos anos censo.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet(params?: GetAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet$Params, context?: HttpContext): Promise<AppSchemasConectividadeAnaliseTemporalResponse> {
    const resp = this.getAnaliseTemporalConectividadeConectividadeAnaliseTemporalGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<AppSchemasConectividadeAnaliseTemporalResponse>): AppSchemasConectividadeAnaliseTemporalResponse => r.body);
  }

}
