/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { FiltrosResponse } from '../models/filtros-response';
import { getFiltrosFiltrosGet } from '../fn/filtros/get-filtros-filtros-get';
import { GetFiltrosFiltrosGet$Params } from '../fn/filtros/get-filtros-filtros-get';

@Injectable({ providedIn: 'root' })
export class FiltrosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getFiltrosFiltrosGet()` */
  static readonly GetFiltrosFiltrosGetPath = '/filtros';

  /**
   * Filtros aplicáveis (genérico, compartilhável entre painéis).
   *
   * Retorna as opções de filtro aplicáveis (municípios, anos, rede de ensino
   * e tipo de localização) para popular dropdowns do frontend. Buscado uma única
   * vez e reaproveitado por todos os painéis. Com `?painel=<nome>`, anexa as
   * métricas específicas daquele painel.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFiltrosFiltrosGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFiltrosFiltrosGet$Response(params?: GetFiltrosFiltrosGet$Params, context?: HttpContext): Promise<StrictHttpResponse<FiltrosResponse>> {
    const obs = getFiltrosFiltrosGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Filtros aplicáveis (genérico, compartilhável entre painéis).
   *
   * Retorna as opções de filtro aplicáveis (municípios, anos, rede de ensino
   * e tipo de localização) para popular dropdowns do frontend. Buscado uma única
   * vez e reaproveitado por todos os painéis. Com `?painel=<nome>`, anexa as
   * métricas específicas daquele painel.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFiltrosFiltrosGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFiltrosFiltrosGet(params?: GetFiltrosFiltrosGet$Params, context?: HttpContext): Promise<FiltrosResponse> {
    const resp = this.getFiltrosFiltrosGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<FiltrosResponse>): FiltrosResponse => r.body);
  }

}
