/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { healthCheckGet } from '../fn/health/health-check-get';
import { HealthCheckGet$Params } from '../fn/health/health-check-get';

@Injectable({ providedIn: 'root' })
export class HealthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `healthCheckGet()` */
  static readonly HealthCheckGetPath = '/';

  /**
   * Health check.
   *
   * Verifica se a API está no ar. Usada por load balancers e ferramentas de monitoramento para confirmar que o processo está respondendo.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `healthCheckGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthCheckGet$Response(params?: HealthCheckGet$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = healthCheckGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Health check.
   *
   * Verifica se a API está no ar. Usada por load balancers e ferramentas de monitoramento para confirmar que o processo está respondendo.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `healthCheckGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthCheckGet(params?: HealthCheckGet$Params, context?: HttpContext): Promise<any> {
    const resp = this.healthCheckGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

}
