/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AppSchemasInfraestruturaAnaliseTemporalResponse } from '../models/app-schemas-infraestrutura-analise-temporal-response';
import { AppSchemasInfraestruturaMapaResponse } from '../models/app-schemas-infraestrutura-mapa-response';
import { getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet } from '../fn/infraestrutura/get-analise-temporal-infraestrutura-infraestrutura-analise-temporal-get';
import { GetAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet$Params } from '../fn/infraestrutura/get-analise-temporal-infraestrutura-infraestrutura-analise-temporal-get';
import { getMapaInfraestruturaInfraestruturaMapaGet } from '../fn/infraestrutura/get-mapa-infraestrutura-infraestrutura-mapa-get';
import { GetMapaInfraestruturaInfraestruturaMapaGet$Params } from '../fn/infraestrutura/get-mapa-infraestrutura-infraestrutura-mapa-get';
import { getPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet } from '../fn/infraestrutura/get-painel-escolas-infraestrutura-infraestrutura-painel-escolas-get';
import { GetPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet$Params } from '../fn/infraestrutura/get-painel-escolas-infraestrutura-infraestrutura-painel-escolas-get';
import { getPainelInfraestruturaInfraestruturaPainelGet } from '../fn/infraestrutura/get-painel-infraestrutura-infraestrutura-painel-get';
import { GetPainelInfraestruturaInfraestruturaPainelGet$Params } from '../fn/infraestrutura/get-painel-infraestrutura-infraestrutura-painel-get';
import { PainelEscolasResponse } from '../models/painel-escolas-response';
import { PainelResponse } from '../models/painel-response';

@Injectable({ providedIn: 'root' })
export class InfraestruturaService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPainelInfraestruturaInfraestruturaPainelGet()` */
  static readonly GetPainelInfraestruturaInfraestruturaPainelGetPath = '/infraestrutura/painel';

  /**
   * Painel de infraestrutura (gráficos + cards).
   *
   * Retorna o painel completo de infraestrutura: cards de total de escolas,
   * tab_percent (barras horizontais por município), barras por dependência e
   * por tipo de localização para a(s) métrica(s) escolhida(s).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPainelInfraestruturaInfraestruturaPainelGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelInfraestruturaInfraestruturaPainelGet$Response(params?: GetPainelInfraestruturaInfraestruturaPainelGet$Params, context?: HttpContext): Promise<StrictHttpResponse<PainelResponse>> {
    const obs = getPainelInfraestruturaInfraestruturaPainelGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Painel de infraestrutura (gráficos + cards).
   *
   * Retorna o painel completo de infraestrutura: cards de total de escolas,
   * tab_percent (barras horizontais por município), barras por dependência e
   * por tipo de localização para a(s) métrica(s) escolhida(s).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPainelInfraestruturaInfraestruturaPainelGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelInfraestruturaInfraestruturaPainelGet(params?: GetPainelInfraestruturaInfraestruturaPainelGet$Params, context?: HttpContext): Promise<PainelResponse> {
    const resp = this.getPainelInfraestruturaInfraestruturaPainelGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<PainelResponse>): PainelResponse => r.body);
  }

  /** Path part for operation `getPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet()` */
  static readonly GetPainelEscolasInfraestruturaInfraestruturaPainelEscolasGetPath = '/infraestrutura/painel/escolas';

  /**
   * Gráfico paginado de métricas de infraestrutura por escola.
   *
   * Retorna uma página do gráfico de métricas por escola (barras empilhadas,
   * ordenado por score DESC) + metadados de paginação.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet$Response(params?: GetPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet$Params, context?: HttpContext): Promise<StrictHttpResponse<PainelEscolasResponse>> {
    const obs = getPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Gráfico paginado de métricas de infraestrutura por escola.
   *
   * Retorna uma página do gráfico de métricas por escola (barras empilhadas,
   * ordenado por score DESC) + metadados de paginação.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet(params?: GetPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet$Params, context?: HttpContext): Promise<PainelEscolasResponse> {
    const resp = this.getPainelEscolasInfraestruturaInfraestruturaPainelEscolasGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<PainelEscolasResponse>): PainelEscolasResponse => r.body);
  }

  /** Path part for operation `getMapaInfraestruturaInfraestruturaMapaGet()` */
  static readonly GetMapaInfraestruturaInfraestruturaMapaGetPath = '/infraestrutura/mapa';

  /**
   * Escolas com score e classificação de infraestrutura (on-the-fly).
   *
   * Retorna as escolas de silver.infraestrutura_comum (uma por escola por ano
   * censo) com as 17 métricas e o score (0–17) e classificação
   * (Boa/Média/Baixa/Inexistente) calculados on-the-fly — não há tabela de score
   * pré-computada na camada gold para infraestrutura.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMapaInfraestruturaInfraestruturaMapaGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMapaInfraestruturaInfraestruturaMapaGet$Response(params?: GetMapaInfraestruturaInfraestruturaMapaGet$Params, context?: HttpContext): Promise<StrictHttpResponse<AppSchemasInfraestruturaMapaResponse>> {
    const obs = getMapaInfraestruturaInfraestruturaMapaGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Escolas com score e classificação de infraestrutura (on-the-fly).
   *
   * Retorna as escolas de silver.infraestrutura_comum (uma por escola por ano
   * censo) com as 17 métricas e o score (0–17) e classificação
   * (Boa/Média/Baixa/Inexistente) calculados on-the-fly — não há tabela de score
   * pré-computada na camada gold para infraestrutura.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMapaInfraestruturaInfraestruturaMapaGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMapaInfraestruturaInfraestruturaMapaGet(params?: GetMapaInfraestruturaInfraestruturaMapaGet$Params, context?: HttpContext): Promise<AppSchemasInfraestruturaMapaResponse> {
    const resp = this.getMapaInfraestruturaInfraestruturaMapaGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<AppSchemasInfraestruturaMapaResponse>): AppSchemasInfraestruturaMapaResponse => r.body);
  }

  /** Path part for operation `getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet()` */
  static readonly GetAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGetPath = '/infraestrutura/analise-temporal';

  /**
   * Evolução temporal da infraestrutura (por localização e por dependência).
   *
   * Retorna os gráficos de evolução temporal: por tipo de localização
   * (uma linha por urbana/rural) e por tipo de dependência administrativa
   * (uma linha por Federal/Estadual/Municipal/Privada), ambos ao longo
   * dos anos censo.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet$Response(params?: GetAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet$Params, context?: HttpContext): Promise<StrictHttpResponse<AppSchemasInfraestruturaAnaliseTemporalResponse>> {
    const obs = getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Evolução temporal da infraestrutura (por localização e por dependência).
   *
   * Retorna os gráficos de evolução temporal: por tipo de localização
   * (uma linha por urbana/rural) e por tipo de dependência administrativa
   * (uma linha por Federal/Estadual/Municipal/Privada), ambos ao longo
   * dos anos censo.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet(params?: GetAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet$Params, context?: HttpContext): Promise<AppSchemasInfraestruturaAnaliseTemporalResponse> {
    const resp = this.getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<AppSchemasInfraestruturaAnaliseTemporalResponse>): AppSchemasInfraestruturaAnaliseTemporalResponse => r.body);
  }

}
