/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppSchemasInfraestruturaAnaliseTemporalResponse } from '../../models/app-schemas-infraestrutura-analise-temporal-response';

export interface GetAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet$Params {

/**
 * Métrica de infraestrutura a plotar nos dois gráficos.
 */
  metrica?: 'in_agua_potavel' | 'in_energia_rede_publica' | 'in_esgoto_rede_publica' | 'in_lixo_servico_coleta' | 'in_banheiro' | 'in_banheiro_pne' | 'in_biblioteca' | 'in_sala_leitura' | 'in_laboratorio_ciencias' | 'in_laboratorio_informatica' | 'in_sala_multiuso' | 'in_sala_atendimento_especial' | 'in_cozinha' | 'in_refeitorio' | 'in_quadra_esportes' | 'in_patio_coberto' | 'in_auditorio';

/**
 * Filtra escolas por participação no PIBID. true = só com PIBID; false = só sem PIBID; omitido = todas.
 */
  pibid?: (boolean | null);
}

export function getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet(http: HttpClient, rootUrl: string, params?: GetAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AppSchemasInfraestruturaAnaliseTemporalResponse>> {
  const rb = new RequestBuilder(rootUrl, getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet.PATH, 'get');
  if (params) {
    rb.query('metrica', params.metrica, {});
    rb.query('pibid', params.pibid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppSchemasInfraestruturaAnaliseTemporalResponse>;
    })
  );
}

getAnaliseTemporalInfraestruturaInfraestruturaAnaliseTemporalGet.PATH = '/infraestrutura/analise-temporal';
