/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppSchemasInfraestruturaMapaResponse } from '../../models/app-schemas-infraestrutura-mapa-response';

export interface GetMapaInfraestruturaInfraestruturaMapaGet$Params {

/**
 * Ano do censo escolar (nu_ano_censo). Se omitido, retorna todos os anos.
 */
  ano?: (number | null);

/**
 * Filtro AND: a escola precisa ter TODAS as variáveis marcadas > 0. Use o parâmetro repetido: ?variaveis=in_agua_potavel&variaveis=in_biblioteca.
 */
  variaveis?: (Array<'in_agua_potavel' | 'in_energia_rede_publica' | 'in_esgoto_rede_publica' | 'in_lixo_servico_coleta' | 'in_banheiro' | 'in_banheiro_pne' | 'in_biblioteca' | 'in_sala_leitura' | 'in_laboratorio_ciencias' | 'in_laboratorio_informatica' | 'in_sala_multiuso' | 'in_sala_atendimento_especial' | 'in_cozinha' | 'in_refeitorio' | 'in_quadra_esportes' | 'in_patio_coberto' | 'in_auditorio'> | null);

/**
 * Filtra escolas por participação no PIBID. true = só com PIBID; false = só sem PIBID; omitido = todas.
 */
  pibid?: (boolean | null);
}

export function getMapaInfraestruturaInfraestruturaMapaGet(http: HttpClient, rootUrl: string, params?: GetMapaInfraestruturaInfraestruturaMapaGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AppSchemasInfraestruturaMapaResponse>> {
  const rb = new RequestBuilder(rootUrl, getMapaInfraestruturaInfraestruturaMapaGet.PATH, 'get');
  if (params) {
    rb.query('ano', params.ano, {});
    rb.query('variaveis', params.variaveis, {});
    rb.query('pibid', params.pibid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppSchemasInfraestruturaMapaResponse>;
    })
  );
}

getMapaInfraestruturaInfraestruturaMapaGet.PATH = '/infraestrutura/mapa';
