/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PainelResponse } from '../../models/painel-response';

export interface GetPainelInfraestruturaInfraestruturaPainelGet$Params {

/**
 * Ano do censo escolar (ex: 2024). Se omitido, agrega todos os censos.
 */
  ano?: (number | null);

/**
 * Lista de municípios (até 4). Use o parâmetro repetido: ?municipios=Belém&municipios=Ananindeua. Se omitido, o tab_percent cobre todos os municípios do recorte.
 */
  municipios?: (Array<string> | null);

/**
 * Filtro AND: escolas precisam ter TODAS as variáveis marcadas = 1.
 */
  variaveis?: (Array<'in_agua_potavel' | 'in_energia_rede_publica' | 'in_esgoto_rede_publica' | 'in_lixo_servico_coleta' | 'in_banheiro' | 'in_banheiro_pne' | 'in_biblioteca' | 'in_sala_leitura' | 'in_laboratorio_ciencias' | 'in_laboratorio_informatica' | 'in_sala_multiuso' | 'in_sala_atendimento_especial' | 'in_cozinha' | 'in_refeitorio' | 'in_quadra_esportes' | 'in_patio_coberto' | 'in_auditorio'> | null);

/**
 * Rede(s) de ensino: Federal, Estadual, Municipal, Privada.
 */
  rede_ensino?: (Array<'Federal' | 'Estadual' | 'Municipal' | 'Privada'> | null);

/**
 * Localização da escola: Urbana ou Rural.
 */
  tp_localizacao?: (Array<'Urbana' | 'Rural'> | null);

/**
 * Filtra escolas por participação no PIBID. true = só com PIBID; false = só sem PIBID; omitido = todas.
 */
  pibid?: (boolean | null);
}

export function getPainelInfraestruturaInfraestruturaPainelGet(http: HttpClient, rootUrl: string, params?: GetPainelInfraestruturaInfraestruturaPainelGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PainelResponse>> {
  const rb = new RequestBuilder(rootUrl, getPainelInfraestruturaInfraestruturaPainelGet.PATH, 'get');
  if (params) {
    rb.query('ano', params.ano, {});
    rb.query('municipios', params.municipios, {});
    rb.query('variaveis', params.variaveis, {});
    rb.query('rede_ensino', params.rede_ensino, {});
    rb.query('tp_localizacao', params.tp_localizacao, {});
    rb.query('pibid', params.pibid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PainelResponse>;
    })
  );
}

getPainelInfraestruturaInfraestruturaPainelGet.PATH = '/infraestrutura/painel';
